[project]
name = "benchmark"
version = "1.1"
description = "Benchmarking tool for evaluating machine performance for data science tasks."
requires-python = ">=3.14, <3.15"
dependencies = [
    "joblib~=1.5",
    "numpy~=2.4",
    "psutil~=7.2",
    "rich~=14.3",
    "torch~=2.10",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu130", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true
